version: "3.9" 
services:
   some-mongo:
     image: mongo:latest
     volumes:
       - DBDATA:/data/db
     restart: always
     networks: 
        - lemoncode-challenge
   topics-api:
     depends_on:
       - some-mongo
     build: 
      context: ./backend
     restart: always
     networks: 
       - lemoncode-challenge
   frontend-js:
     build:
      context: ./frontend
     depends_on:
       - topics-api
     networks:
       - lemoncode-challenge
     ports:
       - 8080:3000
volumes:
    DBDATA: 
networks:
    lemoncode-challenge: 
